-- Auto-generated by scripts/copy-and-gen-sql.cjs.
-- Single UPDATE that maps menu item rows to /menu/<filename>.jpg URLs.
-- Images live in client/public/menu/ (committed in this PR) so they're
-- served statically at the corresponding paths.
--
-- Idempotent: re-running just overwrites with the same value.
-- Square sync preserves imageUrl on update when Square has no image
-- (the current case for every item) — so these survive re-syncs.

UPDATE menuItems SET imageUrl = CASE
  WHEN id = 1 THEN '/menu/1-momo-bubble-meal.jpg'  -- #1 Momo Bubble Meal
  WHEN id = 2 THEN '/menu/2-wrap-bubble-meal.jpg'  -- #2 Wrap Bubble Meal
  WHEN id = 3 THEN '/menu/mixed-grill-kebab.jpg'  -- #3 Kebab Plate Bubble
  WHEN id = 4 THEN '/menu/4-mixed-grill-bubble.jpg'  -- #4 Mixed Grill Bubble
  WHEN id = 5 THEN '/menu/6-family-feast.jpg'  -- #6 Family Feast
  WHEN id = 6 THEN '/menu/mixed-grill-kebab.jpg'  -- ANY 22.99 KEBAB MAIN + BUBBLE TEA
  WHEN id = 7 THEN '/menu/mixed-grill-kebab.jpg'  -- ANY 21.99 KEBAB MAIN + BUBBLE TEA
  WHEN id = 8 THEN '/menu/kofta-wrap.jpg'  -- ANY WRAP + BUBBLE TEA
  WHEN id = 9 THEN '/menu/lychee-rose-oolong.jpg'  -- Bubble Tea
  WHEN id = 10 THEN '/menu/buff-momo.jpg'  -- Buff Momo
  WHEN id = 11 THEN '/menu/buff-momo.jpg'  -- Buff Momo (6pcs)
  WHEN id = 12 THEN '/menu/buff-momo.jpg'  -- BUFF MOMO + BUBBLE TEA
  WHEN id = 13 THEN '/menu/buff-momo.jpg'  -- Buff Momo Platter
  WHEN id = 14 THEN '/menu/vegan-momo-6-pcs.jpg'  -- Cabbage Momo (6pcs)
  WHEN id = 15 THEN '/menu/carrot-dip.jpg'  -- Carrot Dip
  WHEN id = 16 THEN '/menu/chicken-shish-wrap.jpg'  -- Chicken Doner Wrap
  WHEN id = 17 THEN '/menu/chicken-shish-wrap.jpg'  -- CHICKEN DONER WRAP + BUBBLE TEA
  WHEN id = 18 THEN '/menu/chicken-shish-kebab.jpg'  -- Chicken Kebab
  WHEN id = 19 THEN '/menu/chicken-momo.jpg'  -- Chicken Momo
  WHEN id = 20 THEN '/menu/chicken-momo-6pcs.jpg'  -- Chicken Momo (6pcs)
  WHEN id = 21 THEN '/menu/chicken-momo.jpg'  -- CHICKEN MOMO + BUBBLE TEA
  WHEN id = 22 THEN '/menu/chicken-momo.jpg'  -- Chicken Momo Platter
  WHEN id = 23 THEN '/menu/chicken-shish-kebab.jpg'  -- chicken Shish Kebab
  WHEN id = 24 THEN '/menu/chicken-shish-wrap.jpg'  -- Chicken Shish Wrap
  WHEN id = 25 THEN '/menu/chicken-spring-roll.jpg'  -- Chicken Spring Roll
  WHEN id = 26 THEN '/menu/chocolate-momo-2pcs.jpg'  -- Chocolate Momo (2pcs)
  WHEN id = 27 THEN '/menu/mixed-grill-kebab.jpg'  -- Doner main
  WHEN id = 28 THEN '/menu/falafel-and-haloumi-wrap.jpg'  -- Falafel and Haloumi Wrap
  WHEN id = 29 THEN '/menu/hummus-with-pita-bread.jpg'  -- Hummus with Pita Bread
  WHEN id = 30 THEN '/menu/iskender-kebab.jpg'  -- Iskender kebab
  WHEN id = 31 THEN '/menu/kofta-main.jpg'  -- Kofta main
  WHEN id = 32 THEN '/menu/kofta-wrap.jpg'  -- Kofta Wrap
  WHEN id = 33 THEN '/menu/kofta-wrap.jpg'  -- Lamb Doner Wrap
  WHEN id = 34 THEN '/menu/lamb-shish-kebab.jpg'  -- Lamb Kebab
  WHEN id = 35 THEN '/menu/kofta-main.jpg'  -- Lamb Kofta
  WHEN id = 36 THEN '/menu/lamb-meatball-with-rice.jpg'  -- Lamb Meatball with Rice
  WHEN id = 37 THEN '/menu/lamb-meatball-with-rice.jpg'  -- Lamb meatball with rice Bowl
  WHEN id = 38 THEN '/menu/lamb-shish-kebab.jpg'  -- Lamb Shish Kebab
  WHEN id = 39 THEN '/menu/chicken-shish-wrap.jpg'  -- Lamb Shish Wrap
  WHEN id = 40 THEN '/menu/lamb-shish-kebab.jpg'  -- Lamb Sish
  WHEN id = 41 THEN '/menu/lamb-spring-roll.jpg'  -- Lamb Spring Roll
  WHEN id = 42 THEN '/menu/laphing.png'  -- Lhaphing
  WHEN id = 44 THEN '/menu/mediterranean-salad.jpg'  -- Mediterranean Salad
  WHEN id = 45 THEN '/menu/mixed-grill-kebab.jpg'  -- Mixed Grill Kebab
  WHEN id = 46 THEN '/menu/paneer-momo.jpg'  -- Paneer Momo
  WHEN id = 47 THEN '/menu/paneer-momo-6pcs.jpg'  -- Paneer Momo (6pcs)
  WHEN id = 48 THEN '/menu/paneer-momo.jpg'  -- PANEER MOMO + BUBBLE TEA
  WHEN id = 49 THEN '/menu/paneer-momo-platter.jpg'  -- Paneer Momo Platter
  WHEN id = 50 THEN '/menu/hummus-with-pita-bread.jpg'  -- Pita Bread
  WHEN id = 51 THEN '/menu/lamb-spring-roll.jpg'  -- Spinach and Fetta Spring Roll
  WHEN id = 52 THEN '/menu/trio-of-dip.jpg'  -- Trio of Dip
  WHEN id = 53 THEN '/menu/tzatziki-with-pita-bread.jpg'  -- Tzatziki with Pita Bread
  WHEN id = 54 THEN '/menu/vegan-momo.jpg'  -- Vegan Momo
  WHEN id = 55 THEN '/menu/vegan-momo-6-pcs.jpg'  -- Vegan Momo 6 pcs
  WHEN id = 56 THEN '/menu/vegan-momo.jpg'  -- vegetarian Momo
  WHEN id = 57 THEN '/menu/vegan-momo-6-pcs.jpg'  -- vegetarian Momo 6
  WHEN id = 58 THEN '/menu/5-dinner-for-two.jpg'  -- #5 Dinner For two
  WHEN id = 59 THEN '/menu/laphing.png'  -- 2 Lhaphing Special
  WHEN id = 61 THEN '/menu/cappucino.jpg'  -- Cappucino
  WHEN id = 62 THEN '/menu/latte.jpg'  -- Chai Latte
  WHEN id = 63 THEN '/menu/coca-cola-zero-sugar-can.jpg'  -- Coca-Cola 600ml
  WHEN id = 64 THEN '/menu/coca-cola-zero-sugar-can.jpg'  -- Coca-Cola Can
  WHEN id = 65 THEN '/menu/coca-cola-zero-sugar-can.jpg'  -- Coca-Cola Zero Sugar 600ml
  WHEN id = 66 THEN '/menu/coca-cola-zero-sugar-can.jpg'  -- Coca-Cola Zero Sugar Can
  WHEN id = 67 THEN '/menu/latte.jpg'  -- Dirty Chai Latte
  WHEN id = 68 THEN '/menu/espresso.jpg'  -- Espresso
  WHEN id = 69 THEN '/menu/fanta-orange-can.jpg'  -- Fanta Orange Can
  WHEN id = 70 THEN '/menu/flat-white.jpg'  -- Flat White
  WHEN id = 71 THEN '/menu/6-family-feast.jpg'  -- FRIDAY-FEAST FRIDAY
  WHEN id = 74 THEN '/menu/yuzu-green-tea-fizz.jpg'  -- Fuze Mango & Green Tea
  WHEN id = 76 THEN '/menu/hot-chocolate.jpg'  -- Hot Chocolate
  WHEN id = 77 THEN '/menu/hot-chocolate.jpg'  -- Ice Chocolate
  WHEN id = 78 THEN '/menu/ice-latte.jpg'  -- Ice Latte
  WHEN id = 79 THEN '/menu/ice-long-black.jpg'  -- Ice Long Black
  WHEN id = 82 THEN '/menu/latte.jpg'  -- Latte
  WHEN id = 83 THEN '/menu/lemonade-can.jpg'  -- Lemonade Can
  WHEN id = 84 THEN '/menu/long-black.jpg'  -- Long Black
  WHEN id = 85 THEN '/menu/macchiato.jpg'  -- Macchiato
  WHEN id = 86 THEN '/menu/mocha.jpg'  -- Mocha
  WHEN id = 87 THEN '/menu/mocha-jelly-boba.jpg'  -- Mocha Jelly Boba
  WHEN id = 88 THEN '/menu/chicken-momo.jpg'  -- Momo Monday
  WHEN id = 89 THEN '/menu/chicken-momo.jpg'  -- Momo Special Chicken
  WHEN id = 91 THEN '/menu/piccolo.jpg'  -- Piccolo
  WHEN id = 95 THEN '/menu/salted-caramel-machhiato-boba.jpg'  -- Salted Caramel Machhiato Boba
  WHEN id = 96 THEN '/menu/samosa.jpg'  -- Samosa
  WHEN id = 97 THEN '/menu/snack-pack.jpg'  -- Snack Pack
  WHEN id = 98 THEN '/menu/spanish-latte-boba.jpg'  -- Spanish Latte Boba
  WHEN id = 99 THEN '/menu/sprite-can.jpg'  -- Sprite Can
  WHEN id = 100 THEN '/menu/chicken-momo.jpg'  -- THU (MOMO) — STAFF & STUDENT FAVES (ID)
  WHEN id = 101 THEN '/menu/kofta-wrap.jpg'  -- THU (WRAP) — STAFF & STUDENT FAVES (ID) REQUIRED
  WHEN id = 102 THEN '/menu/tiramisu-cream-coffee-boba.jpg'  -- Tiramisu Cream Coffee Boba
  WHEN id = 103 THEN '/menu/mixed-grill-kebab.jpg'  -- Tuesday Turiksh Kebab day
  WHEN id = 104 THEN '/menu/vietnamese-boba-coffee.jpg'  -- Vietnamese Boba Coffee
  WHEN id = 105 THEN '/menu/kofta-wrap.jpg'  -- WED- WRAP WEDNESDAY
  ELSE imageUrl
END
WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 74, 76, 77, 78, 79, 82, 83, 84, 85, 86, 87, 88, 89, 91, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105);
